### ISSUE TITLE
pip failes because requirements is missing

### ISSUE THREAD

**Issue by almostserious** [lagmoellertim/freenet-funk-api#6]
`pip install freenet-funk-api` failes with the following error:

```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5HzpqK/freenet-funk-api/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by lagmoellertim** [comment]
Hey, first off all, the official name in pip is funkapi. I need to update my readme. But since you are using Mac OS or Linux and this library is python 3 only, try pip3 install funkapi.
That should do the trick.

**Comment by almostserious** [comment]
Ah yes indeed. I seem to have caught another PyPi Version of this. funkapi works fine :) Thank you

**Comment by lagmoellertim** [comment]
No problem!
